#!/usr/bin/bash

scripts=$HOME/Scripts


/usr/lib/polkit-kde-authentication-agent-1 &

killall dunst
dunst &

# wallpaper
swww init
$scripts/update_wallpaper &

# waybar
$scripts/launch_waybar &
sleep 2

# applets
pasystray &
#nm-applet &

#jellyfin-mpv-shim &

export $(dbus-launch) 
