#!/usr/bin/bash

scripts=$HOME/Scripts

/usr/lib/polkit-kde-authentication-agent-1 &

killall dunst
dunst &

# wallpaper
swww init
$scripts/update_wallpaper &

# waybar
$scripts/launch_waybar &
sleep 2

# applets
pasystray &

# xdph
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-gnome
killall xdg-desktop-portal-kde
killall xdg-desktop-portal-lxqt
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
sleep 1
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
