max-gamma = 150

profile {
    time = 7:30
    identity = true
}

profile {
    time = 21:00
    temperature = 4000
    gamma = 0.7
}

profile {
    time = 23:00
    temperature = 2800
    gamma = 0.7
}
