#!/usr/bin/env sh

# Options for powermenu
logout=" Logout"
shutdown=" Shutdown"
reboot=" Reboot"

# Get answer from user via rofi
selected_option=$(printf '%s\n' "$logout" "$reboot" "$shutdown" | rofi -dmenu\
                  -i\
                  -p "Power"\
                  -config "$HOME/.config/rofi/powermenu.rasi"\
                  -width "15"\
                  -lines 3\
                  -line-margin 3\
                  -line-padding 10\
                  -scrollbar-width "0" )

case "$selected_option" in
    "$logout")
        loginctl terminate-session "$XDG_SESSION_ID"
        ;;
    "$shutdown")
        systemctl poweroff
        ;;
    "$reboot")
        systemctl reboot
        ;;
esac
