#!/usr/bin/env sh

# Options for powermenu
logout=" Logout"
shutdown=" Shutdown"
reboot=" Reboot"

# Get answer from user via rofi
selected_option=$(echo "$logout
$reboot
$shutdown" | rofi -dmenu\
                  -i\
                  -p "Power"\
                  -config "~/.config/rofi/powermenu.rasi"\
                  -width "15"\
                  -lines 3\
                  -line-margin 3\
                  -line-padding 10\
                  -scrollbar-width "0" )

# Do something based on selected option
if [ "$selected_option" == "$logout" ]
then
    $HOME/Scripts/stop_hyprland
elif [ "$selected_option" == "$shutdown" ]
then
    systemctl poweroff
elif [ "$selected_option" == "$reboot" ]
then
    systemctl reboot
else
    echo "No match"
fi
