#!/usr/bin/env fish

figlet -f big UPGRADING!

if test (hostname) = tempora
    figlet -f small pegasus
    ssh pegasus "doas apk update && doas apk upgrade --available"

    figlet -f small stuxnet
    ssh stuxnet "doas apk update && doas apk upgrade --available"

    figlet -f small genoa
    ssh genoa "sudo apt update && sudo apt full-upgrade && sudo ./update_chromedriver.sh"
end

figlet -f small (hostname)

rustup update

bun upgrade

flatpak update

yay
